### ISSUE TITLE
请问作者是不是少了PeopleRelation2.csv文件

### ISSUE THREAD

**Issue by plutoloy** [CCP101/visual-kg-history#17]

**Comment by CCP101** [comment]
PeopleRelation2.csv文件为标准的以三元组CSV文件格式存储的知识图谱信息，且该文件需要自行制作，因此该文件不开源。如有需要可以自行制作三元组CSV文件并修改文件名后导入该系统以使用

**Comment by CCP101** [comment]
本系统已结束开发，暂停维护，欢迎fork后在此基础上开发，并欢迎就代码运行相关的问题继续提问，此Issue将关闭。
